### ISSUE TITLE
Issue while seeing the python notebook in repo

### ISSUE THREAD

**Issue by wasimkhan33** [wasimkhan33/Bank-Marketing-Effectiveness-Prediction#1]
![image](https://user-images.githubusercontent.com/55997315/147363193-a666838c-b285-43d5-a93d-64b1ece1206d.png)

Facing issue while opening python notebook

**Comment by ganzagun** [comment]
Try uploading colab notebook directly on github. Sometimes ipynb is not able to load in github.
Use this link https://www.geeksforgeeks.org/how-to-upload-project-on-github-from-google-colab/ .

**Comment by wasimkhan33** [comment]
Thank you for your help on this, issue is resolved now somehow. Maybe the issue is with internet speed.
